### ISSUE TITLE
Fix "TextEditor constructor is no longer public"

### ISSUE THREAD

**Issue by Coteh** [Coteh/syntaxdb-atom-plugin#4]
As reported in specs:

"The TextEditor constructor is no longer public.

To construct a text editor, use atom.workspace.buildTextEditor(). To check if an object is a text editor, use atom.workspace.isTextEditor(object).

at Object.TextEditor (C:\Users\James\AppData\Local\atom\app-1.9.6\resources\app.asar\exports\atom.js:38:14)
at Function.content (C:\Users\James\Documents\Development Projects\syntaxdb-atom-plugin\lib\SyntaxSearchView.js:27:44)
at Function.<anonymous> (C:\Users\James\Documents\Development Projects\syntaxdb-atom-plugin\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:156:31)
at Function.buildHtml (C:\Users\James\Documents\Development Projects\syntaxdb-atom-plugin\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:123:10)
at SyntaxSearchView.constructor (C:\Users\James\Documents\Development Projects\syntaxdb-atom-plugin\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:155:33)
at new SyntaxSearchView (C:\Users\James\Documents\Development Projects\syntaxdb-atom-plugin\lib\SyntaxSearchView.js:40:86)
at Object.TextEditor (C:\Users\James\AppData\Local\atom\app-1.9.6\resources\app.asar\exports\atom.js:38:14)
at Function.content (C:\Users\James\Documents\Development Projects\syntaxdb-atom-plugin\lib\SyntaxResultNotesTab.js:33:40)
at Function.<anonymous> (C:\Users\James\Documents\Development Projects\syntaxdb-atom-plugin\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:156:31)
at Function.buildHtml (C:\Users\James\Documents\Development Projects\syntaxdb-atom-plugin\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:123:10)
at SyntaxResultNotesTab.constructor (C:\Users\James\Documents\Development Projects\syntaxdb-atom-plugin\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:155:33)
at SyntaxResultNotesTab.SyntaxResultTab (C:\Users\James\Documents\Development Projects\syntaxdb-atom-plugin\lib\SyntaxResultTab.js:23:85)
at Object.TextEditor (C:\Users\James\AppData\Local\atom\app-1.9.6\resources\app.asar\exports\atom.js:38:14)
at Function.content (C:\Users\James\Documents\Development Projects\syntaxdb-atom-plugin\lib\SyntaxResultSyntaxTab.js:33:41)
at Function.<anonymous> (C:\Users\James\Documents\Development Projects\syntaxdb-atom-plugin\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:156:31)
at Function.buildHtml (C:\Users\James\Documents\Development Projects\syntaxdb-atom-plugin\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:123:10)
at SyntaxResultSyntaxTab.constructor (C:\Users\James\Documents\Development Projects\syntaxdb-atom-plugin\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:155:33)
at SyntaxResultSyntaxTab.SyntaxResultTab (C:\Users\James\Documents\Development Projects\syntaxdb-atom-plugin\lib\SyntaxResultTab.js:23:85)
at Object.TextEditor (C:\Users\James\AppData\Local\atom\app-1.9.6\resources\app.asar\exports\atom.js:38:14)
at Function.content (C:\Users\James\Documents\Development Projects\syntaxdb-atom-plugin\lib\SyntaxResultExampleTab.js:41:41)
at Function.<anonymous> (C:\Users\James\Documents\Development Projects\syntaxdb-atom-plugin\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:156:31)
at Function.buildHtml (C:\Users\James\Documents\Development Projects\syntaxdb-atom-plugin\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:123:10)
at SyntaxResultExampleTab.constructor (C:\Users\James\Documents\Development Projects\syntaxdb-atom-plugin\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:155:33)
at SyntaxResultExampleTab.SyntaxResultTab (C:\Users\James\Documents\Development Projects\syntaxdb-atom-plugin\lib\SyntaxResultTab.js:23:85)
at Object.TextEditor (C:\Users\James\AppData\Local\atom\app-1.9.6\resources\app.asar\exports\atom.js:38:14)
at Function.content (C:\Users\James\Documents\Development Projects\syntaxdb-atom-plugin\lib\SyntaxResultDocumentationTab.js:37:40)
at Function.<anonymous> (C:\Users\James\Documents\Development Projects\syntaxdb-atom-plugin\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:156:31)
at Function.buildHtml (C:\Users\James\Documents\Development Projects\syntaxdb-atom-plugin\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:123:10)
at SyntaxResultDocumentationTab.constructor (C:\Users\James\Documents\Development Projects\syntaxdb-atom-plugin\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:155:33)
at SyntaxResultDocumentationTab.SyntaxResultTab (C:\Users\James\Documents\Development Projects\syntaxdb-atom-plugin\lib\SyntaxResultTab.js:23:85)"

**Comment by Coteh** [comment]
https://github.com/atom/atom/commit/fe0b7b8de3a88e7453273972303ac5a47b0cc7c0

Sometime after this issue was originally posted, they started exporting the constructor again.
